from __future__ import annotations

from typing import Any, AsyncIterator, Protocol

from susie_core import AgentModelOption


class AgentRuntime(Protocol):
    async def new_session(self) -> str: ...
    async def load_system_instruction_if_needed(self, instruction: str) -> None: ...
    async def list_model_opts(self) -> list[AgentModelOption]: ...
    async def model(self) -> str | None: ...
    async def set_model(self, value: str) -> bool: ...
    async def cancel(self) -> None: ...
    def prompt(self, parts: list[str]) -> AsyncIterator[Any]: ...
